# Generated by Django 5.1.7 on 2025-10-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='users_about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
